Teams:
  - name: 'Red'
    color: '#B02E26'
  - name: 'Orange'
    color: '#F9801D'
  - name: 'Yellow'
    color: '#FED83D'
  - name: 'Lime'
    color: '#80C71F'
  - name: 'Green'
    color: '#5E7C16'
  - name: 'Cyan'
    color: '#169C9C'
  - name: 'Light Blue'
    color: '#3AB3DA'
  - name: 'Blue'
    color: '#3C44AA'
  - name: 'Purple'
    color: '#8932B8'
  - name: 'Magenta'
    color: '#C74EBD'
  - name: 'Pink'
    color: '#F38BAA'
  - name: 'Brown'
    color: '#835432'
  - name: 'Black'
    color: '#1D1D21'
  - name: 'Gray'
    color: '#474F52'
  - name: 'Light Gray'
    color: '#9D9D97'
  - name: 'White'
    color: '#F9FFFE'
  - name: 'God'
    color: '#F7E983'