@startuml
'https://plantuml.com/class-diagram

class Tower {
    -blocks : ArrayList<BlockState>
    -corners : int[][]
    -towerBase : int
}

class TowerCommands {
    -towerListener : TowerListener
    +onCommand() : boolean
}

class TowerListener {
    -towers : EnumMap<Teams, Tower>
    -blockSets : BlockSets
    -isTowering : boolean
    -cancelEvents : boolean
    -plugin : JavaPlugin
    +enableTower()
    +disableTower()
    +enableEvents()
    +disableEvents()
    +removeBlocks()

    +onPlaceBlock()
    +onBreakBlock()
    +onBlockBurn()
    +onBlockSpread()
    +onBlockExplode()
    +onEntityExplode()
    +onBlockFade()
    +onBlockPistonExtend()
    +onBlockPistonRetract()
    +onSpongeAbsorb()
    +onTNTPrime()
    +onBlockGrow()
    +onBlockForm()
    +onEntityChangeBlock()
    +onPlayerShearBlock()
}

class BlockSets {
    +fallingBlocks : EnumSet<Material>
    +fullBlocks : EnumSet<Material>
}

enum Team {
    RED,
    ORANGE,
    YELLOW,
    LIME,
    GREEN,
    CYAN,
    LIGHT_BLUE,
    BLUE,
    PURPLE,
    MAGENTA,
    PINK,
    BLACK,
    BROWN,
    GRAY,
    LIGHT_GRAY,
    WHITE
}

@enduml